project:
  name: quickstart-drupal
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - us-east-1
  - us-east-2
  - us-west-2
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - ap-southeast-2
  s3_bucket: ''
  s3_regional_buckets: false
  shorten_stack_name: true
  parameters:
    AutoScalingNotificationEmail: 'foo@example.com'
    AvailabilityZones: $[taskcat_getaz_2]
    BastionAMIOS: Amazon-Linux2-HVM
    BastionInstanceType: t2.micro
    CloudFrontAlias: cdn.default
    CloudFrontPriceClass: use-all-edge-locations
    DBAutoMinorVersionUpgrade: 'true'
    DBBackupRetentionPeriod: '7'
    DBInstanceClass: db.t3.small
    DBMultiAZ: 'true'
    DBMainUsername: dbadmin
    DBMainUserPassword: $[taskcat_genpass_10]
    DrupalDbPassword: $[taskcat_genpass_10]
    DrupalSiteAdminPassword: $[taskcat_genpass_10]
    DrupalSiteAdminEmail: foo@example.com
    DrupalDbName: drupaldb
    DrupalDbUsername: drupal
    DrupalSiteAdminUsername: drupaladmin
    DrupalSiteDomain: localhost.local
    DrupalSiteName: Drupal Test Site
    ElastiCacheAutoMinorVersionUpgrade: 'true'
    ElastiCacheEnable: 'true'
    ElastiCacheNodeType: cache.t3.micro
    ElastiCacheNumberOfNodes: '2'
    PhpVersion: 'php7.4'
    RemoteAccessCIDR: 10.0.0.0/16
    Route53HostedZoneId: ''
    SSLCertificateId: ''
    VPCCIDR: 10.0.0.0/16
    WebServerDesiredCapacity: '2'
    WebServerInstanceType: t3.medium
    WebServerMaxSize: '4'
    WebServerMinSize: '1'
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: 'us-east-1'
tests:
  drupal-v7-no-cdn:
    parameters:
      CloudFrontEnable: 'false'
      DrupalVersion: '7'
      KeyPair: $[taskcat_getkeypair]
    regions:
    - ap-southeast-2
    - eu-central-1
    s3_bucket: ''
    template: templates/drupal-master.template.yaml
  drupal-v9-cdn:
    parameters:
      CloudFrontEnable: 'true'
      DrupalVersion: '9'
      KeyPair: $[taskcat_getkeypair]
    regions:
      - eu-west-1
      - us-east-1
    s3_bucket: ''
    template: templates/drupal-master.template.yaml
  drupal-v8-no-cdn:
    parameters:
      CloudFrontEnable: 'false'
      DrupalVersion: '8'
      KeyPair: $[taskcat_getkeypair]
    regions:
      - us-east-2
      - us-west-2
    s3_bucket: ''
    template: templates/drupal-master.template.yaml
  drupal-v9-no-cdn:
    parameters:
      CloudFrontEnable: 'false'
      DrupalVersion: '9'
      KeyPair: $[taskcat_getkeypair]
    regions:
      - eu-west-2
    s3_bucket: ''
    template: templates/drupal-master.template.yaml
