AWSTemplateFormatVersion: '2010-09-09'
Description: Create Route53 RecordSet for Drupal site domain (qs-1s5hh8p8o)
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Drupal Site Domain Configuration
        Parameters:
          - HostedZoneId
          - DomainName
          - ElbDnsName
          - ElbHostedZoneId
    ParameterLabels:
      HostedZoneId:
        default: Route53 Hosted Zone ID
      DomainName:
        default: Drupal site domain name
      ElbDnsName:
        default: ALB/ELB URL
      ElbHostedZoneId:
        default: ALB/ELB Hosted Zone ID
Parameters:
  HostedZoneId:
    Description: Route53 Hosted Zone ID
    Type: AWS::Route53::HostedZone::Id
  DomainName:
    Description: Drupal site domain name. e.g. mysite.com.
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: (?!-)[a-zA-Z0-9-.]*(?<!-)
    ConstraintDescription: must be a valid fully-qualified domain name.
    Default: example.com
  ElbDnsName:
    Description: ALB/ELB URL
    Type: String
  ElbHostedZoneId:
    Description: ALB/ELB Hosted Zone ID e.g. Z2FDTNDATAQYW2
    Type: String
Resources:
  DrupalDomainDns:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      RecordSets:
        - Name: !Ref 'DomainName'
          Type: A
          AliasTarget:
            DNSName: !Ref 'ElbDnsName'
            EvaluateTargetHealth: true
            HostedZoneId: !Ref 'ElbHostedZoneId'
